CREATE TABLE `mints21` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jobState` VARCHAR(255) DEFAULT NULL,
  `surface` VARCHAR(255) DEFAULT NULL,
  `obstacle` VARCHAR(255) DEFAULT NULL,
  `figure` VARCHAR(255) DEFAULT NULL,
  `openSea` VARCHAR(255) DEFAULT NULL,
  `ipfsGIF` VARCHAR(255) DEFAULT NULL,
  `ipfsJPG` VARCHAR(255) DEFAULT NULL,
  `ipfsMP4` VARCHAR(255) DEFAULT NULL,
  `ipfsMP3` VARCHAR(255) DEFAULT NULL,
  `ipfsGLB` VARCHAR(255) DEFAULT NULL,
  `ipfsJSON` VARCHAR(255) DEFAULT NULL,
  `mintprice` VARCHAR(100) DEFAULT NULL,
  `fullname` VARCHAR(100) DEFAULT NULL,
  `mintdate` DATETIME DEFAULT CURRENT_TIMESTAMP(),
  `buyerAddress` VARCHAR(255) DEFAULT NULL,
  `buytxHash` VARCHAR(255) DEFAULT NULL,
  `blockHeight` INT DEFAULT NULL,
  `fallDistance` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

GRANT SELECT ON downonly.mints21 TO 'frontend'@'%';
GRANT SELECT, UPDATE, INSERT ON downonly.mints21 TO 'renderer'@'%';
